# Simple Linear Regression

Largely inspired by https://www.kaggle.com/code/sushaldevasari1306/simplelinearregression

* Matplotlib is replaced with Plotly Express for more simplicity and better visualization
* Dataset is local
* Small evolutions in the code

## Import des packages

In [3]:
import numpy as np
import pandas as pd
import plotly.express as px

## Import et vérification du jeu de données

In [4]:
df = pd.read_csv('./salary-data.csv')

In [5]:
df.head()

   Unnamed: 0  Experience Years  Salary
0           1               1.1   39343
1           2               1.2   42774
2           3               1.3   46205
3           4               1.5   37731
4           5               2.0   43525

## removing unnecessary columns

In [6]:
df.drop(columns=["Unnamed: 0"], axis=1, inplace=True)

## Checking for Null Values

In [7]:
df.isnull().sum()

Experience Years    0
Salary              0
dtype: int64

## Check for correlation

In [8]:
df.corr()

                  Experience Years    Salary
Experience Years          1.000000  0.977692
Salary                    0.977692  1.000000

## visualizing data points using plotly express

In [9]:
plot = px.scatter(
    df,
    x='Experience Years',
    y='Salary',
    title='Salary vs YearsExperience')
plot.show()

## independent and dependent features

In [10]:
X = df[['Experience Years']]  ## avoiding series datatype for the input features
y = df['Salary']

## Performing train test split

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

## Standardization

In [13]:
from sklearn.preprocessing import StandardScaler

In [14]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)  ## avoiding data leakage

In [15]:
## Applying Linear Regression

In [16]:
from sklearn.linear_model import LinearRegression

regression = LinearRegression()

In [17]:
regression.fit(X_train, y_train)

LinearRegression()

In [18]:
print("Coefficient or slope: ", regression.coef_)
print("Intercept: ", regression.intercept_)

Coefficient or slope:  [24735.17118781]
Intercept:  74915.20000000001

## Plotting Training data for best fit line using plotly

In [19]:

plot = px.scatter(
    x=X_train.flatten(),
    y=y_train,
    title='Salary vs YearsExperience',
    labels={'x': 'Experience Years', 'y': 'Salary'}
)
plot.add_scatter(x=X_train.flatten(), y=regression.predict(X_train), mode='lines', name='Best Fit Line')
plot.show()

## Prediction

In [20]:
y_pred = regression.predict(X_test)

## Performance Metrics

### MAE, RSE, RMSE

In [21]:
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [22]:
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mse)
print("MSE: ", mse)
print("MAE: ", mae)
print("RMSE ou écart quadratique moyen: ", rmse)

MSE:  40884772.62082657
MAE:  5793.506861825283
RMSE ou écart quadratique moyen:  6394.120160024096

### R-square

In [23]:
from sklearn.metrics import r2_score

score = r2_score(y_test, y_pred)
print("R2: ", score)

print("R2 ajusté: ", (1 - (1 - score) * (len(y_test) - 1) / (len(y_test) - X_test.shape[1] - 1)))

R2:  0.9426749383532557
R2 ajusté:  0.9355093056474126